(function () {
    var imglib = [
{
    "sheetname": "playersheet",
    "type": "player",
    "src": "library/playersheet.png",
    "width": 384,
    "height": 48,
    "framewidth": 48,
    "frameheight": 48,
    "framedelay": 2,
    "framesperdirection": 2,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "monstersheet",
    "type": "monster",
    "src": "library/monstersheet.png",
    "width": 256,
    "height": 128,
    "framewidth": 32,
    "frameheight": 32,
    "framedelay": 4,
    "framesperdirection": 2,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "numberssheet",
    "type": "numbers",
    "src": "library/numbers.png",
    "width": 240,
    "height": 48,
    "framewidth": 24,
    "frameheight": 48,
    "framedelay": 0,
    "framesperdirection": 0,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "explosionsheet",
    "type": "explosion",
    "src": "library/explosion.png",
    "width": 96,
    "height": 16,
    "framewidth": 16,
    "frameheight": 16,
    "framedelay": 4,
    "framesperdirection": 5,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "playermissilesheet",
    "type": "playermissile",
    "src": "library/playermissile.png",
    "width": 16,
    "height": 16,
    "framewidth": 16,
    "frameheight": 16,
    "framedelay": 0,
    "framesperdirection": 1,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "sparksheet",
    "type": "spark",
    "src": "library/spark.png",
    "width": 16,
    "height": 16,
    "framewidth": 16,
    "frameheight": 16,
    "framedelay": 0,
    "framesperdirection": 1,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "entitysheet",
    "type": "entity",
    "src": "library/entities.png",
    "width": 64,
    "height": 160,
    "framewidth": 32,
    "frameheight": 32,
    "framedelay": 4,
    "framesperdirection": 2,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "zoltarsheet",
    "type": "zoltar",
    "src": "library/zoltarsheet.png",
    "width": 384,
    "height": 48,
    "framewidth": 48,
    "frameheight": 48,
    "framedelay": 2,
    "framesperdirection": 2,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
},
{
    "sheetname": "markersheet",
    "type": "marker",
    "src": "library/marker.png",
    "width": 128,
    "height": 32,
    "framewidth": 32,
    "frameheight": 32,
    "framedelay": 1,
    "framesperdirection": 3,
    "deathframe": 0,
    "deathframecount": 0,
    "attackframe": 0,
    "attackframecount": 0,
    "painframe": 0,
    "painframecount": 0
}
];
    window.wizardwars = window.wizardwars || {};
    window.wizardwars.imglib = imglib;
})();